import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";
import Image from "next/image";

const nunito = localFont({
  src: "./fonts/Nunito-Regular.otf",
  variable: "--font-nunito",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Roh Garuda",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.variable}`}>
        <div className="container-body">
          <Image
            src="/img/Background.svg"
            alt="Descriptive text for screen readers"
            layout="fill"
            className="background-image"
          />
          <div className="children-content">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
